import Providers from "@/app/components/Providers";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import Header from "./components/Header/Header";
import "./styles/globals.scss";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${montserrat.variable} ${interSans.variable}`} suppressHydrationWarning>
        <Header />
        <Providers>{children}</Providers>
        {children}
      </body>
    </html>
  );
}
